# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/protos/python/feature_extraction/feature_extraction.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=src/protos/python/feature_extraction/feature_extraction.proto\"K\n\x08ImgBatch\x12\x10\n\x08imgs_pkl\x18\x01 \x01(\x0c\x12\x15\n\rcam_label_pkl\x18\x02 \x01(\x0c\x12\x16\n\x0eview_label_pkl\x18\x03 \x01(\x0c\"$\n\x0c\x46\x65\x61tureBatch\x12\x14\n\x0c\x66\x65\x61tures_pkl\x18\x01 \x01(\x0c\x32\x37\n\x10\x46\x65\x61tureExtractor\x12#\n\x07predict\x12\t.ImgBatch\x1a\r.FeatureBatchb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.protos.python.feature_extraction.feature_extraction_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMGBATCH']._serialized_start=65
  _globals['_IMGBATCH']._serialized_end=140
  _globals['_FEATUREBATCH']._serialized_start=142
  _globals['_FEATUREBATCH']._serialized_end=178
  _globals['_FEATUREEXTRACTOR']._serialized_start=180
  _globals['_FEATUREEXTRACTOR']._serialized_end=235
# @@protoc_insertion_point(module_scope)
